# Generated by Django 4.2.7 on 2024-01-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_firstname', models.CharField(max_length=60)),
                ('user_lastname', models.CharField(blank=True, max_length=60, null=True)),
                ('user_department', models.CharField(max_length=60)),
                ('user_designation', models.CharField(max_length=60)),
                ('user_role', models.CharField(max_length=60)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
