# Generated by Django 3.1.13 on 2024-01-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240104_0207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='scholarship',
        ),
    ]
